---
abstract: 'Present your object for comparison purposes'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Comparable
provides:
  Data::Comparable:
    file: lib/Data/Comparable.pm
    version: 1.100840
requires:
  Carp: 0
  Data::Dumper: 0
  Data::Inherited: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Scalar::Util: 0
  Test::More: 0.88
  UNIVERSAL::require: 0
  YAML: 0
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Comparable
  homepage: http://search.cpan.org/dist/Data-Comparable/
  repository: http://github.com/hanekomu/Data-Comparable
version: 1.100840
